// GENERATED by tools/sprites/build.js — do not edit by hand.
// Run `npm run sprites` after changing anything under tools/sprites/.

export const SHEET = '/sprites.png';
export const TILE = 32;
export const SHEET_W = 512;
export const SHEET_H = 240;

/** Ship sprites, drawn bow-right; the client rotates for vertical placement. */
export const SHIPS = {
  carrier: { x: 0, y: 0, w: 160, h: 32 },
  battleship: { x: 160, y: 0, w: 128, h: 32 },
  cruiser: { x: 288, y: 0, w: 96, h: 32 },
  submarine: { x: 384, y: 0, w: 96, h: 32 },
  destroyer: { x: 0, y: 32, w: 64, h: 32 },
};

/** 16 island autotiles in one row, indexed by neighbour mask N=1 E=2 S=4 W=8. */
export const ISLAND_Y = 64;
export const ISLAND_COUNT = 16;

/** National flags, keyed by country id. */
export const FLAGS = {
  us: { x: 0, y: 96, w: 48, h: 32 },
  uk: { x: 48, y: 96, w: 48, h: 32 },
  jp: { x: 96, y: 96, w: 48, h: 32 },
  de: { x: 144, y: 96, w: 48, h: 32 },
  ru: { x: 192, y: 96, w: 48, h: 32 },
  cn: { x: 240, y: 96, w: 48, h: 32 },
  ir: { x: 288, y: 96, w: 48, h: 32 },
  es: { x: 336, y: 96, w: 48, h: 32 },
};

/** Power-up icons, keyed by pickup type. */
export const ICONS = {
  mine: { x: 0, y: 128, w: 32, h: 32 },
  radar: { x: 32, y: 128, w: 32, h: 32 },
  extra: { x: 64, y: 128, w: 32, h: 32 },
  repair: { x: 96, y: 128, w: 32, h: 32 },
  recharge: { x: 128, y: 128, w: 32, h: 32 },
};

/** Looping hurricane frames, and the one-shot explosion. Both are strips. */
export const STORM = { y: 160, size: 32, frames: 8 };
export const BOOM = { y: 192, size: 48, frames: 8 };
