// Builds client/sprites.png and client/sprite-map.js from the art modules.
//
//   npm run sprites
//
// The sheet is a build ARTEFACT that is committed, so the game still needs no build
// step to run — you only re-run this when the art changes.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { Raster } from './raster.js';
import { encodePNG } from './png.js';
import { drawShip } from './ships.js';
import { drawIsland } from './islands.js';
import { drawFlag } from './flags.js';
import {
  drawIcon, drawStorm, drawBoom, ICON_KINDS, STORM_FRAMES, BOOM_FRAMES,
} from './effects.js';
import { FLEET } from '../../shared/constants.js';
import { COUNTRY_IDS } from '../../shared/countries.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CLIENT = path.resolve(HERE, '../../client');

const TILE = 32;
const SHEET_W = 512;
const ISLAND_COUNT = 16; // one tile per N/E/S/W neighbour bitmask

// ---------------------------------------------------------------- layout

const ships = FLEET.map((f) => ({ type: f.type, len: f.len, art: drawShip(f.type, f.len, TILE) }));
for (const s of ships) {
  if (s.art.w !== s.len * TILE || s.art.h !== TILE) {
    throw new Error(`${s.type}: expected ${s.len * TILE}x${TILE}, got ${s.art.w}x${s.art.h}`);
  }
}

// Pack ships left to right, wrapping to a new TILE-tall row when the sheet runs out.
const placed = [];
let x = 0;
let y = 0;
for (const s of ships) {
  if (x + s.art.w > SHEET_W) { x = 0; y += TILE; }
  placed.push({ ...s, x, y });
  x += s.art.w;
}

// Islands always start their own row so the client can address them with the simple
// evenly-spaced background-position formula.
const islandY = y + TILE;
const islands = [];
for (let mask = 0; mask < ISLAND_COUNT; mask++) {
  const art = drawIsland(mask, TILE);
  if (art.w !== TILE || art.h !== TILE) {
    throw new Error(`island ${mask}: expected ${TILE}x${TILE}, got ${art.w}x${art.h}`);
  }
  islands.push({ mask, art, x: mask * TILE, y: islandY });
}

// Flags get their own row too. They are 3:2, so eight of them fit a 512 sheet exactly.
const FLAG_W = TILE * 1.5;
const flagY = islandY + TILE;
const flags = COUNTRY_IDS.map((id, i) => {
  const art = drawFlag(id, TILE);
  if (art.w !== FLAG_W || art.h !== TILE) {
    throw new Error(`flag ${id}: expected ${FLAG_W}x${TILE}, got ${art.w}x${art.h}`);
  }
  return { id, art, x: i * FLAG_W, y: flagY };
});
if (flags.length * FLAG_W > SHEET_W) throw new Error('flag row overflows the sheet');

// Item icons: one row, used both in the tray and on radar-revealed squares.
const iconY = flagY + TILE;
const icons = ICON_KINDS.map((kind, i) => {
  const art = drawIcon(kind, TILE);
  if (art.w !== TILE || art.h !== TILE) {
    throw new Error(`icon ${kind}: expected ${TILE}x${TILE}, got ${art.w}x${art.h}`);
  }
  return { kind, art, x: i * TILE, y: iconY };
});

// The storm: one row of rotation frames that loop.
const stormY = iconY + TILE;
const storm = Array.from({ length: STORM_FRAMES }, (_, f) => {
  const art = drawStorm(f, TILE);
  if (art.w !== TILE || art.h !== TILE) {
    throw new Error(`storm frame ${f}: expected ${TILE}x${TILE}, got ${art.w}x${art.h}`);
  }
  return { art, x: f * TILE, y: stormY };
});

// The explosion, played once. Bigger than a cell so the blast overspills it.
const BOOM = TILE * 1.5;
const boomY = stormY + TILE;
const boom = Array.from({ length: BOOM_FRAMES }, (_, f) => {
  const art = drawBoom(f, BOOM);
  if (art.w !== BOOM || art.h !== BOOM) {
    throw new Error(`boom frame ${f}: expected ${BOOM}x${BOOM}, got ${art.w}x${art.h}`);
  }
  return { art, x: f * BOOM, y: boomY };
});
if (icons.length * TILE > SHEET_W) throw new Error('icon row overflows the sheet');
if (storm.length * TILE > SHEET_W) throw new Error('storm row overflows the sheet');
if (boom.length * BOOM > SHEET_W) throw new Error('boom row overflows the sheet');

const SHEET_H = boomY + BOOM;

// ---------------------------------------------------------------- compose

const sheet = new Raster(SHEET_W, SHEET_H);
for (const s of placed) sheet.blit(s.art, s.x, s.y);
for (const i of islands) sheet.blit(i.art, i.x, i.y);
for (const f of flags) sheet.blit(f.art, f.x, f.y);
for (const i of icons) sheet.blit(i.art, i.x, i.y);
for (const s of storm) sheet.blit(s.art, s.x, s.y);
for (const b of boom) sheet.blit(b.art, b.x, b.y);

const png = encodePNG(SHEET_W, SHEET_H, sheet.data);
fs.writeFileSync(path.join(CLIENT, 'sprites.png'), png);

const manifest = `// GENERATED by tools/sprites/build.js — do not edit by hand.
// Run \`npm run sprites\` after changing anything under tools/sprites/.

export const SHEET = '/sprites.png';
export const TILE = ${TILE};
export const SHEET_W = ${SHEET_W};
export const SHEET_H = ${SHEET_H};

/** Ship sprites, drawn bow-right; the client rotates for vertical placement. */
export const SHIPS = {
${placed.map((s) => `  ${s.type}: { x: ${s.x}, y: ${s.y}, w: ${s.art.w}, h: ${s.art.h} },`).join('\n')}
};

/** 16 island autotiles in one row, indexed by neighbour mask N=1 E=2 S=4 W=8. */
export const ISLAND_Y = ${islandY};
export const ISLAND_COUNT = ${ISLAND_COUNT};

/** National flags, keyed by country id. */
export const FLAGS = {
${flags.map((f) => `  ${f.id}: { x: ${f.x}, y: ${f.y}, w: ${f.art.w}, h: ${f.art.h} },`).join('\n')}
};

/** Power-up icons, keyed by pickup type. */
export const ICONS = {
${icons.map((i) => `  ${i.kind}: { x: ${i.x}, y: ${i.y}, w: ${TILE}, h: ${TILE} },`).join('\n')}
};

/** Looping hurricane frames, and the one-shot explosion. Both are strips. */
export const STORM = { y: ${stormY}, size: ${TILE}, frames: ${STORM_FRAMES} };
export const BOOM = { y: ${boomY}, size: ${BOOM}, frames: ${BOOM_FRAMES} };
`;
fs.writeFileSync(path.join(CLIENT, 'sprite-map.js'), manifest);

console.log(`sprites.png  ${SHEET_W}x${SHEET_H}  (${(png.length / 1024).toFixed(1)} KB)`);
for (const s of placed) console.log(`  ${s.type.padEnd(11)} ${s.art.w}x${s.art.h} @ ${s.x},${s.y}`);
console.log(`  islands     ${ISLAND_COUNT} tiles @ 0,${islandY}`);
console.log(`  flags       ${flags.length} @ 0,${flagY}`);
console.log(`  icons       ${icons.length} @ 0,${iconY}`);
console.log(`  storm       ${storm.length} frames @ 0,${stormY}`);
console.log(`  boom        ${boom.length} frames of ${BOOM}px @ 0,${boomY}`);
