// Builds client/sprites.png and client/sprite-map.js from the art modules.
//
//   npm run sprites
//
// The sheet is a build ARTEFACT that is committed, so the game still needs no build
// step to run — you only re-run this when the art changes.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { Raster } from './raster.js';
import { encodePNG } from './png.js';
import { drawShip } from './ships.js';
import { drawIsland } from './islands.js';
import { FLEET } from '../../shared/constants.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CLIENT = path.resolve(HERE, '../../client');

const TILE = 32;
const SHEET_W = 512;
const ISLAND_COUNT = 16; // one tile per N/E/S/W neighbour bitmask

// ---------------------------------------------------------------- layout

const ships = FLEET.map((f) => ({ type: f.type, len: f.len, art: drawShip(f.type, f.len, TILE) }));
for (const s of ships) {
  if (s.art.w !== s.len * TILE || s.art.h !== TILE) {
    throw new Error(`${s.type}: expected ${s.len * TILE}x${TILE}, got ${s.art.w}x${s.art.h}`);
  }
}

// Pack ships left to right, wrapping to a new TILE-tall row when the sheet runs out.
const placed = [];
let x = 0;
let y = 0;
for (const s of ships) {
  if (x + s.art.w > SHEET_W) { x = 0; y += TILE; }
  placed.push({ ...s, x, y });
  x += s.art.w;
}

// Islands always start their own row so the client can address them with the simple
// evenly-spaced background-position formula.
const islandY = y + TILE;
const islands = [];
for (let mask = 0; mask < ISLAND_COUNT; mask++) {
  const art = drawIsland(mask, TILE);
  if (art.w !== TILE || art.h !== TILE) {
    throw new Error(`island ${mask}: expected ${TILE}x${TILE}, got ${art.w}x${art.h}`);
  }
  islands.push({ mask, art, x: mask * TILE, y: islandY });
}

const SHEET_H = islandY + TILE;

// ---------------------------------------------------------------- compose

const sheet = new Raster(SHEET_W, SHEET_H);
for (const s of placed) sheet.blit(s.art, s.x, s.y);
for (const i of islands) sheet.blit(i.art, i.x, i.y);

const png = encodePNG(SHEET_W, SHEET_H, sheet.data);
fs.writeFileSync(path.join(CLIENT, 'sprites.png'), png);

const manifest = `// GENERATED by tools/sprites/build.js — do not edit by hand.
// Run \`npm run sprites\` after changing anything under tools/sprites/.

export const SHEET = '/sprites.png';
export const TILE = ${TILE};
export const SHEET_W = ${SHEET_W};
export const SHEET_H = ${SHEET_H};

/** Ship sprites, drawn bow-right; the client rotates for vertical placement. */
export const SHIPS = {
${placed.map((s) => `  ${s.type}: { x: ${s.x}, y: ${s.y}, w: ${s.art.w}, h: ${s.art.h} },`).join('\n')}
};

/** 16 island autotiles in one row, indexed by neighbour mask N=1 E=2 S=4 W=8. */
export const ISLAND_Y = ${islandY};
export const ISLAND_COUNT = ${ISLAND_COUNT};
`;
fs.writeFileSync(path.join(CLIENT, 'sprite-map.js'), manifest);

console.log(`sprites.png  ${SHEET_W}x${SHEET_H}  (${(png.length / 1024).toFixed(1)} KB)`);
for (const s of placed) console.log(`  ${s.type.padEnd(11)} ${s.art.w}x${s.art.h} @ ${s.x},${s.y}`);
console.log(`  islands     ${ISLAND_COUNT} tiles @ 0,${islandY}`);
